### ISSUE TITLE
Autograder fails on doctest

### ISSUE THREAD

**Issue by oliverosz** [oliverosz/doctest-autograder-bug#1]
Dear @ashishkeshan, I see you're maintaining [education/autograding-python-grader](https://github.com/education/autograding-python-grader). Could you look at the bug seen in this example?

`pytest.ini` contains `addopts = --doctest-modules` to make pytest run doctests.

Running `pytest` locally collects and runs the doctest then reports the test as passed.

Th autograder called in the classroom workflow runs into an internal error when running pytest. See the output of the pytest step in the [workflow log](https://github.com/oliverosz/doctest-autograder-bug/actions/runs/8736071600/job/23970193452).

**Comment by ashishkeshan** [comment]
hey @oliverosz, I believe the issue is that the `autograding-python-grader` is using its own pytest.ini file which is defined here: https://github.com/education/autograding-python-grader/blob/main/pytest.ini. Unfortunately it won't be leveraging the `pytest.ini` you've defined here. Maybe you can throw something in the setup command to modify the contents of the `pytest.ini` but I haven't quite tested that yet.

**Comment by ashishkeshan** [comment]
Looks like our python-grader code has an assumption that there will be line numbers given for all of the  tests, which is why things still seem to be failing.

**Comment by ashishkeshan** [comment]
You might have better luck just using the `command-grader` and then creating the `pytest.ini` file in the setup command of that run.

**Comment by ashishkeshan** [comment]
@oliverosz check out https://github.com/ashishkeshan/doctest-autograder-bug/blob/main/.github/workflows/classroom.yml, I got it to work with this setup!

**Comment by oliverosz** [comment]
@ashishkeshan Thanks for the help! Then I will use the `command-grader` for checking the doctests.
